#!/bin/sh

if [ -f ~/.vimrc ] ; then
    echo "Your config file has been moved to ~/.vimrc.~previous"
    mv ~/.vimrc ~/.vimrc.~previous
fi

# remove previous version
if [ -d ~/.vim ] ; then
    rm -rf .vim
fi

git clone https://github.com/rfussien/.vim.git
cd .vim

# update the external vundle project (cf https://github.com/gmarik/vundle)
git submodule init
git submodule update

# link the .vimrc
ln -s ~/.vim/vimrc ~/.vimrc
touch ~/.my.vimrc

# install bundles
vi +PluginInstall +qall

echo "Done!"
